import styles from '../styles/Home.module.css';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import {useState} from "react";
import {useRouter} from "next/router";

const Home: NextPage = () => {

    const router = useRouter();
    const [to, setTo] = useState<string>("");
    const [from, setFrom] = useState<string>("");

    return (
        <div className={styles.container}>
            <Head>
                <title>ggwp</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>ggwp</h1>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.js</code>
                </p>

                <div className={styles.grid}>

                    <div className={styles.card}>
                        <h2>ggwp</h2>
                        <p>Create a simple ggwp message to share with your friends </p>
                    </div>

                    <div className={styles.card}>
                        <input type={"text"} placeholder={"to"} onChange={e => setTo(e.target.value)}/>
                        <input type={"text"} placeholder={"from"} onChange={e => setFrom(e.target.value)}/>
                        <button onClick={() => {router.push({pathname: "/ggwp", query: {to: to, from: from}})}}>create</button>
                    </div>
                </div>
            </main>

            <footer className={styles.footer}>
                <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
                    Powered by{' '}
                    <span className={styles.logo}>
                    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
}

export default Home;
